import './globals.css'

import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import Aside from '@/components/layout/Aside'
import Navigation from '@/components/layout/Navigation'
import Particles from '@/components/Particles'

import ToastContainer from "@/compLibs/ToastContainer"

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-[#112548] relative ${montserrat.className}`}>
        <Particles isVisible={true}/>
        <section className='grid lg:grid-cols-[25%75%] lg:container lg:items-start lg:my-2 gap-x-8 gap-y-20 relative z-10'>

          <Aside />

          <section>
            <Navigation />
            <section className='lg:mt-10'>
    <main className="bg-white rounded-md lg:p-4">
              
              {children}
              </main>
              </section>
          </section>
        </section>
        <ToastContainer/>
      </body>
    </html>
  )
}
